export const PHRASES = {
  motivation: [
    "You got this",
    "Believe in yourself",
    "You are capable",
    "You are unstoppable",
    "You are enough",
    "Own your power",
    "Stay positive",
    "Choose to shine",
    "Dream big",
    "Defy the odds",
    "Keep going",
    "Never give up",
    "Stay strong",
    "Make it happen",
    "Trust the process",
    "Stay focused",
    "Keep moving forward",
    "Push your limits",
    "Prove them wrong",
    "Aim high",
    "Work hard",
    "Stay the course",
    "Never back down",
    "Keep pushing",
    "Embrace the journey",
    "Great job",
    "Well done",
    "You are amazing",
    "Be your best",
    "You are brilliant",
  ],
  support_after_failure: [
    "It's okay",
    "Don't worry",
    "Setbacks happen",
    "Shake it off",
    "It takes time",
    "Hang in there",
    "Try again",
    "Keep trying",
    "Bounce back",
    "Start over",
    "You'll get it",
    "Try again tomorrow",
    "It gets better",
    "Learn and grow",
    "Don't lose hope",
  ],
};
